# Generated by Django 6.1.1 on 2026-09-28 01:54

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Welcome text and mission statement for the homepage.'),
        ),
        migrations.CreateModel(
            name='SpeciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('creator_name', models.CharField(blank=True, default='', help_text='Display name if the creator is external or not a registered user.', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to curated showcases.')),
                ('has_content_warning', models.BooleanField(default=False, help_text='Flag for mature themes/body horror.')),
                ('has_oc_exemption', models.BooleanField(default=True, help_text="Displays the '100% Exclusive Character Copyright' protection badge on the page.")),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Species lore, baseline guidelines, and design rules.')),
                ('traits', wagtail.fields.StreamField([('trait', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('core', 'Core Spec (Mandatory)'), ('modular', 'Modular / Optional Add-on'), ('variant', 'Anatomical Variant')]}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('trait_type', 1), ('description', 2), ('image', 3)]], {})}, help_text='Modular anatomical specs and trait breakdowns.')),
                ('license_type', models.CharField(choices=[('CC0', 'CC0 1.0 Universal (Public Domain)'), ('CC_BY', 'CC BY 4.0 (Attribution)'), ('CC_BY_SA', 'CC BY-SA 4.0 (Attribution-ShareAlike)'), ('CC_BY_NC', 'CC BY-NC 4.0 (Attribution-NonCommercial)'), ('CC_BY_NC_SA', 'CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike)'), ('CC_BY_ND', 'CC BY-ND 4.0 (Attribution-NoDerivatives)'), ('CC_BY_NC_ND', 'CC BY-NC-ND 4.0 (Attribution-NonCommercial-NoDerivatives)'), ('OPEN', 'Open Species'), ('CLOSED', 'Closed Species')], default='CC_BY_SA', help_text='Copyleft license applied to this species.', max_length=20)),
                ('additional_assets', wagtail.fields.StreamField([('asset', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('psd', 'PSD / Clip Studio (Layered Art)'), ('blend', '3D Mesh (.blend / .glb)'), ('vector', 'Vector (.svg / .pdf)'), ('lineart', 'PNG Lineart / Base'), ('other', 'Other Source File')]}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('file_type', 1), ('file', 2)]], {})}, help_text='Extra community assets, 3D models, lineart, etc.')),
                ('creator_socials', wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('linktree', 'Linktree'), ('instagram', 'Instagram'), ('bluesky', 'Bluesky'), ('twitter', 'Twitter / X'), ('furaffinity', 'FurAffinity'), ('toyhouse', 'Toyhouse'), ('deviantart', 'DeviantArt'), ('artstation', 'ArtStation'), ('kofi', 'Ko-fi'), ('patreon', 'Patreon'), ('website', 'Personal Website'), ('other', 'Other')]}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})})),
                ('asset_file', models.ForeignKey(blank=True, help_text='Primary downloadable PSD/vector source file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Main preview banner for home grid and header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('creator_user', models.ForeignKey(blank=True, help_text='Registered platform user who created this species.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_species', to=settings.AUTH_USER_MODEL)),
                ('parent_species', models.ForeignKey(blank=True, help_text='Select if this species is a fork/derivative of another species on LibreCritters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='home.speciespage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeciesPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.speciespage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='speciespage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SpeciesPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
